### ISSUE TITLE
Compilation instead of emulation

### ISSUE THREAD

**Issue by GReaperEx** [mintsuki/subleq-emu#4]
Given the abysmal performance of Dawn on any hardware, I propose a change in design:

Instead of emulating every single instruction, we could instead convert/compile the SUBLEQ bytecode into direct CPU machine code. The idea is to let primary code run directly on the hardware, on paged RAM, and handle I/O by means of page faults.

The conversion/compilation speed will depend on whether or not Dawn separates its code from its data, because if it doesn't we'd have to perform an entire analysis of the binary before compiling. Needless to say, this suggestion wouldn't work at all if Dawn engages in self-modifying-code shenanigans.

You may be asking though why go through all this trouble? Compilation by itself won't make it run much faster, since the frequent page faults would offset the gains of direct execution... Ahh, but now, the bytecode can be optimized! We can convert sequences of subleq into faster instructions, for example:
```
0 : subleq A, B, 24
24:

0 : subleq A, A, 24
24:

0 : subleq A, A, off
```
to
```
mov rsi, A
mov rdi, B
mov rax, [rsi]
sub [rdi], rax

mov rdi, A
xor rax, rax
mov [rdi], rax

mov rdi, A
xor rax, rax
mov [rdi], rax
mov rax, off
jmp rax
```
you know, instead of the generic:
```
mov rsi, A
mov rdi, B
mov rax, [rsi]
sub [rdi], rax
jg .skip
mov rax, C
jmp rax
.skip:
```

All addresses of course would have to be converted to the proper endianess during compilation. Or rather, not just addresses but every single qword.

**Comment by GReaperEx** [comment]
After some poking around the Dawn binary, I realized that it most definitely runs self-modifying code. Oh well, so much for that, I guess it'll remain slow as hell...

**Comment by GReaperEx** [comment]
But wait! There is a way to implement this, even with code that modifies itself!
What the "compiler" will have to do is to remap each address, which it would do anyway, in such a way that old addresses of memory offsets fall on-top of the 64-bit immediate fields. 
With this approach though, we would definitely have to analyze the binary to figure out which addresses that are run are also altered, to be able to optimize the ones that are not modified.

**Comment by seriocomedy** [comment]
Too much work tbh and would probably be slower still.

**Comment by GReaperEx** [comment]
It probably is too much work, but why do you say it would be slower?

**Comment by seriocomedy** [comment]
There would have to be analysis on the fly and the checking code would probably run slower than just emulating subleq.
