### ISSUE TITLE
ISO

### ISSUE THREAD

**Issue by Vort** [mintsuki/subleq-emu#7]
In readme file following line exists:
https://github.com/mintsuki/subleq-emu/blob/38abb9063ab0e4c0fef87591e9e91e4dc9715315/README#L1

When I looked inside this archive:
https://github.com/mintsuki/subleq-emu/releases/download/bin-release10/subleq.img.xz
I found `.img` file instead of `.iso` file.

Renaming it to `.iso` did not allowed me to boot it in VirtualBox.
Converting to `.vdi` with `VBoxManage` command succeeded, but I see empty window when launch Disks application, so I'm not sure if such conversion was the right way of solving this problem.

Please either mention in readme that it is HDD image and not ISO 9660 one or convert your image to `.iso` format.

**Comment by Mintsuki** [comment]
Hello, I recommend simply building from source. I probably won't be making any more releases.
